/**
 * The committed photographs, decoded and run through the extractor.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * WHAT THIS TEST IS ACTUALLY ABOUT — READ BEFORE TRUSTING PHASE 7
 * ═══════════════════════════════════════════════════════════════════════════
 * The Phase 7 brief asks what alignment `fixtures/photos/gornergrat-matterhorn.jpg`
 * recovers against the real SRTM terrain in `data/tiles/`. The answer, which
 * has to be said plainly because everything else about this phase depends on
 * it, is: **nothing, and nothing is the correct answer, because that file is
 * not a photograph of anything.**
 *
 * It is a uniform mid-grey frame carrying authored EXIF, generated by
 * `src/exif/testing/generate.ts` so that the EXIF extractor can be tested
 * against real bytes in the real format (see `fixtures/photos/README.md` — the
 * image content is explicitly irrelevant to what it was built for). Decoding it
 * and asking where the sky stops is asking a question the file has no answer
 * to.
 *
 * So this file does NOT establish that the extractor works on real
 * photographs. **Nothing in this repository does, because there is no
 * photograph of a mountain in it** — the ground-truth cases deliberately cite
 * images on Wikimedia Commons rather than vendoring them, and this environment
 * cannot fetch them. What this file establishes is the property that matters
 * when the extractor meets an image it cannot read: it says so, in the shape
 * the type system forces, and no heading reaches the labels.
 *
 * That is the honest state of Phase 7 on real data, and it should be read as a
 * gap in the evidence, not as evidence.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { decode as decodeJpeg } from 'jpeg-js';
import { describe, expect, it } from 'vitest';

import { cameraPoseFromFocalLength } from '../core/projection.js';
import { alignSkyline } from './align.js';
import { extractSkyline } from './skyline.js';
import { signatureProfile } from './testing/profiles.js';
import type { RgbaImage } from './types.js';

const PHOTO_DIR = fileURLToPath(new URL('../../fixtures/photos/', import.meta.url));

function loadPhoto(fileName: string): RgbaImage {
  const decoded = decodeJpeg(readFileSync(join(PHOTO_DIR, fileName)), { useTArray: true });
  return { width: decoded.width, height: decoded.height, data: decoded.data };
}

describe('fixtures/photos/gornergrat-matterhorn.jpg', () => {
  const image = loadPhoto('gornergrat-matterhorn.jpg');

  it('is a 1200×900 frame, as its EXIF fixture declares', () => {
    expect(image.width).toBe(1200);
    expect(image.height).toBe(900);
  });

  it('contains no skyline, because it is a uniform grey frame and not a photograph', () => {
    const skyline = extractSkyline(image);
    expect(skyline.coverage01).toBe(0);
    expect(skyline.meanConfidence01).toBe(0);
    for (const column of skyline.columns) expect(column.rowNorm).toBeUndefined();
  });

  it('refuses to align it, rather than reporting a confident zero offset', () => {
    // The pose is the one this fixture's EXIF actually carries: heading 265.4°
    // true, 28 mm-equivalent on a 4:3 frame. The terrain profile is a
    // stand-in — which terrain is irrelevant, because the photograph side of
    // the correspondence is empty and no profile could rescue it.
    const camera = cameraPoseFromFocalLength({
      headingDeg: 265.4,
      focalLength35mm: 28,
      imageWidthPx: image.width,
      imageHeightPx: image.height,
    });
    const result = alignSkyline(extractSkyline(image), camera, signatureProfile(265, 60));

    expect(result.status).toBe('failed');
    if (result.status !== 'failed') return;
    expect(result.reason).toBe('insufficient-skyline');
    expect(result.diagnostics.usedColumnCount).toBe(0);
    // A zero offset is what a naive implementation would return here, and it
    // would be indistinguishable from "checked, EXIF was right".
    expect(result).not.toHaveProperty('headingOffsetDeg');
    expect(result).not.toHaveProperty('correctedCamera');
  });
});

describe('the other committed fixture photographs', () => {
  // All five are generated grey frames for the EXIF suite. Asserted as a group
  // so that if one is ever replaced with a genuine photograph this test fails
  // and someone has to come and look — which is the outcome we want.
  it.each([
    'chamonix-north-east.jpg',
    'aconcagua-south-west.jpg',
    'dead-sea-below-sea-level.jpg',
    'stripped-no-exif.jpg',
  ])('%s carries no readable skyline either', (fileName) => {
    const skyline = extractSkyline(loadPhoto(fileName));
    expect(skyline.coverage01).toBe(0);
  });
});
