/**
 * Writes the fixture photos to fixtures/photos/.
 *
 *   npx tsx src/exif/testing/generate.ts
 *
 * The generated JPEGs are committed so that the tests parse real files off
 * disk, and `fixtures.test.ts` re-encodes them in memory and asserts byte
 * equality — so editing the fixture definitions without re-running this script
 * fails the suite rather than silently drifting.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { encodeFixture, PHOTO_FIXTURES } from './fixtures';
import { FIXTURE_PHOTO_DIR, fixturePhotoPath } from './paths';

function readme(): string {
  const lines = [
    '# Fixture photos',
    '',
    'Generated by `npx tsx src/exif/testing/generate.ts` from the authored EXIF in',
    '`src/exif/testing/fixtures.ts`. Do not hand-edit — regenerate.',
    '',
    'Each file is a genuine baseline JPEG (a uniform mid-grey frame) carrying exactly',
    'the metadata listed below. The test expectations are computed by hand from these',
    'authored values, never from the extractor output.',
    '',
  ];
  for (const fixture of PHOTO_FIXTURES) {
    lines.push(`## ${fixture.fileName}`, '', fixture.description, '');
    for (const note of fixture.authoredNotes) lines.push(`- ${note}`);
    lines.push('');
  }
  return lines.join('\n');
}

export function writeFixtures(): void {
  mkdirSync(FIXTURE_PHOTO_DIR, { recursive: true });
  for (const fixture of PHOTO_FIXTURES) {
    const bytes = encodeFixture(fixture);
    writeFileSync(fixturePhotoPath(fixture), bytes);
    process.stdout.write(`wrote ${fixture.fileName} (${String(bytes.length)} bytes)\n`);
  }
  writeFileSync(join(FIXTURE_PHOTO_DIR, 'README.md'), readme());
  process.stdout.write('wrote README.md\n');
}

const invokedDirectly =
  process.argv[1] !== undefined && fileURLToPath(import.meta.url) === process.argv[1];
if (invokedDirectly) writeFixtures();
